- hosts: rpis
  vars:
    locale: "es_ES.UTF-8"

  pre_tasks:
    - name: Run apt-get update and apt-get upgrade
      include_tasks:
        file: ./tasks/update.yml

    - name: Install packages
      include_tasks:
        file: ./tasks/packages.yml

  tasks:
  - name: Congratulations!
    debug:
      msg:
        - "Install donner kebab!"

  handlers:
    - name: reboot
      command: shutdown -r +0 'Ansible Reboot triggered'
      async: 0
      poll: 0
      ignore_errors: true
      become: true
      notify: wait for reboot to finish

    - name: wait for reboot to finish
      local_action: wait_for host={{ ansible_host }} state=started port=22 delay=50 timeout=120
      become: false