- hosts: rpis
  vars:
    locale: "es_ES.UTF-8"
    keyboard_layout: "es"
    timezone: Europe/Madrid

  pre_tasks:
    - name: Set GPU memory split
      include_tasks:
        file: ./tasks/set_gpusplit.yml

    - name: Set Internationalization Options
      include_tasks:
        file: ./tasks/internationalization.yml

    - name: Run apt-get update and apt-get upgrade
      include_tasks:
        file: ./tasks/update.yml

    - name: Install packages
      include_tasks:
        file: ./tasks/packages.yml

    - name: Set the hostname
      include_tasks:
        file: ./tasks/hostname.yml

  roles:
    - { role: geerlingguy.pip, become: yes }
    - { role: geerlingguy.docker_arm, become: yes }

  tasks:
  - name: Congratulations!
    debug:
      msg:
        - "Provision donner kebab!"

  handlers:
    - name: reboot
      command: shutdown -r +0 'Ansible Reboot triggered'
      async: 0
      poll: 0
      ignore_errors: true
      become: true
      notify: wait for reboot to finish

    - name: wait for reboot to finish
      local_action: wait_for host={{ ansible_host }} state=started port=22 delay=50 timeout=120
      become: false

    - name: update tzdata
      become: true
      command: dpkg-reconfigure --frontend noninteractive tzdata