- hosts: rpis
  vars:
    locale: "es_ES.UTF-8"
    keyboard_layout: "es"
    timezone: Europe/Madrid

  pre_tasks:
    # Set GPU memory split
    - include_tasks: ./tasks/set_gpusplit.yml
      tags: setup

    # Set Internationalization Options
    - include_tasks: ./tasks/internationalization.yml
      tags: setup

    # Run apt-get update and apt-get upgrade
    - include_tasks: ./tasks/update.yml
      tags: update

    # Install packages
    - include_tasks: ./tasks/packages.yml
      tags: install

    # Set the hostname
    - include_tasks: ./tasks/hostname.yml
      tags: setup

    - include_tasks: ./tasks/tzdata.yml
      tags: system

  roles:
    - { role: geerlingguy.pip, become: yes }
    - { role: geerlingguy.docker_arm, become: yes }

  tasks:
  - name: Congratulations!
    debug:
      msg:
        - "Provision donner kebab!"

  handlers:
    - name: reboot
      command: shutdown -r +0 'Ansible Reboot triggered'
      async: 0
      poll: 0
      ignore_errors: true
      become: true
      notify: wait for reboot to finish

    - name: wait for reboot to finish
      local_action: wait_for host={{ ansible_host }} state=started port=22 delay=50 timeout=120
      become: false