# Run apt-get update and apt-get upgrade
# Depends on: none
#

# Update apt packages
- name: Update apt packages
  become: yes
  ignore_errors: true
  apt: 
    update_cache=yes

# Upgrade apt packages
- name: Upgrade apt packages
  become: yes
  ignore_errors: true
  apt:
    upgrade=dist
